### ISSUE TITLE
Make it possible to define an Other text field via a choices entry

### ISSUE THREAD

**Issue by timhoffm** [Quansight-Labs/typeform-yaml-survey#7]
The current approach for an "Other" with a textfield is an entry `other: true`
```
  - title: 'What is your favorite fruit'
    other: true
    choices:
      - 'Apple'
      - 'Orange'
```

I propose to instead/additionally support a special format convention for such an entry in the `choices` section, e.g. "Other TEXTFIELD". IMHO this makes it much simpler to read and think about the question because the `choices` section then coincides with rendering of the survey.

```
  - title: 'What is your favorite fruit'
    choices:
      - 'Apple'
      - 'Orange'
      - 'Other TEXTFIELD'
```

If there is interest, I can provide a PR.
